'use client'

import "./globals.css";
import { Inter, Space_Grotesk } from "next/font/google";
import Navbar from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });
const SpaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const path = usePathname();
  console.log(path)
  
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="site.html" />
        <link rel="shortcut icon" type="x-icon" href="favicon.ico" />
        <link rel="stylesheet" href="css/font-awesome.min.css" />
        <link rel="stylesheet" href="css/animate.min.css" />
        <link rel="stylesheet" href="css/bootstrap.min.css" />
        <link rel="stylesheet" href="css/jquery.fancybox.css" />
        <link rel="stylesheet" href="css/slicknav.css" />
        <link rel="stylesheet" href="css/magnific-popup.css" />
        <link rel="stylesheet" href="css/owl.carousel.min.css" />
        <link rel="stylesheet" href="css/line-awesome.css" />
        <link rel="stylesheet" href="css/style.css" />
        <link rel="stylesheet" href="css/dark.css" />
        <link rel="stylesheet" href="css/responsive.css" />
        <link
          href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i"
          rel="stylesheet"
        />
      </head>
      <body>
        <div className="body-content " style={{backgroundColor:'black'}}>
        {path !== '/' && path !== '/login' &&path!=='/intrest' ? <Header/> : null}

          {children}{" "}
        </div>
      </body>
    </html>
  );
}
